### PR TITLE
Fixed the typo in "Hackatons"

### LINKED ISSUE #50: Fix the typo in "Hackatons" in top menu
Change "Hackatons" to "Hackathons" in top menu.

event-buddy herokuapp com- laptop with mdpi screen

### PR DESCRIPTION
**Pull request by udit-001**
Fixed it!
Fixes #50

### CODE REVIEW

**Comment by geekyd** [comment]
@udit-001 Seems like your branch is not updates please follow these steps:
1. git reset --hard af2768c21b82372695d5c19b95939aa6bbeee128
2. git pull upstream master
3. Make the changes & create a commit
4. git push -f

**Comment by udit-001** [comment]
Thanks for the tip bro, I'm kinda new to this.
I have fixed it now!

**Comment by geekyd** [comment]
@udit-001 Add fixes #50 in the description. It looks good to merge.
It's great to see you getting involved in open source.

**Comment by udit-001** [comment]
Added the fixed in the description, seems ready to merge!

**Pull request merged**
