### PR TITLE
Add logo and screenshot to Readme

### PR DESCRIPTION
**Pull request by Kevek**

### CODE REVIEW

**Comment by Kevek** [comment]
PR for issue #43

**Comment by geekyd** [comment]
@Kevek Can you please take the screenshot again, there is a typo in the current version. Also move the screenshot to the top, just under the project description

**Comment by Kevek** [comment]
Sure, gimme a few minutes and I'll amend

**Comment by geekyd** [comment]
@Kevek Thank you so much for the PR :)

**Pull request merged**
