### PR TITLE
added NYC hackathons

### PR DESCRIPTION
**Pull request by jkao1**
I have contributed to #7 by adding upcoming hackathons in the New York City area (where I come from).

### CODE REVIEW

**Comment by geekyd** [comment]
@jkao1 Thanks for the PR. Just had one question regarding the list, are these annual events?

**Comment by geekyd** [comment]
@jkao1 Can you please resolve the conflicts?

**Comment by jkao1** [comment]
@geekyd conflicts have been resolved!

**Comment by geekyd** [comment]
@jkao1 Thanks for the PR.

**Pull request merged**
